scheduler: more details in case of failure to get running builds from CircleCI
Prior to this commit, one would get the below, which doesn't help diagnose the issue:
```
  File "/base/data/home/apps/s~positive-cocoa-90213/1.413436923800735358/main.py", line 161, in _get_running_builds
    assert result.status_code == 200
AssertionError
```
We now also log the URL since one could otherwise get:
```
RuntimeError: Failed to get running builds for repository "weaveworks/wks". Status code: 404. Response: {"message":"Project not found"}
```
despite having this URL working well: https://circleci.com/api/v1/project/weaveworks/wks